// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb82evTJct_XPnhJZjTBza7PT40pXnMNo',
    appId: '1:864687919176:web:18071fe32a46bd9edf887d',
    messagingSenderId: '864687919176',
    projectId: 'kmusic-h',
    authDomain: 'kmusic-h.firebaseapp.com',
    storageBucket: 'kmusic-h.firebasestorage.app',
    measurementId: 'G-VSQM771K6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgeVDWJfMv4oppuNG5gO1kVsmtB-wYvo',
    appId: '1:864687919176:android:bb2e17aa991f3e5ddf887d',
    messagingSenderId: '864687919176',
    projectId: 'kmusic-h',
    storageBucket: 'kmusic-h.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcetTpRzspWm53_qGEseNM_4fhK_E_63E',
    appId: '1:864687919176:ios:535e1e3dbb3064c3df887d',
    messagingSenderId: '864687919176',
    projectId: 'kmusic-h',
    storageBucket: 'kmusic-h.firebasestorage.app',
    iosBundleId: 'com.example.kmusich',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcetTpRzspWm53_qGEseNM_4fhK_E_63E',
    appId: '1:864687919176:ios:535e1e3dbb3064c3df887d',
    messagingSenderId: '864687919176',
    projectId: 'kmusic-h',
    storageBucket: 'kmusic-h.firebasestorage.app',
    iosBundleId: 'com.example.kmusich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb82evTJct_XPnhJZjTBza7PT40pXnMNo',
    appId: '1:864687919176:web:0ab0d71590cb4ee6df887d',
    messagingSenderId: '864687919176',
    projectId: 'kmusic-h',
    authDomain: 'kmusic-h.firebaseapp.com',
    storageBucket: 'kmusic-h.firebasestorage.app',
    measurementId: 'G-695KF7S85H',
  );
}
